### ISSUE TITLE
Support optional adopting ownership of AWS cred secret (possibly SSH keys as well)

### ISSUE THREAD

**Issue by dgoodwin** [openshift/hive#109]
SD would like to have the AWS creds secret go away with the cluster deployment. We did not support this as we thought creds would be shared by multiple clusters. However optionally we could add a boolean to the cluster deployment spec indicating it should adopt and own the AWS creds secret. (and probably ssh key secret as well) Controller could then make sure we own these objects as soon as it's possible to do so.

**Comment by dgoodwin** [comment]
Discussed with team, we're thinking this may not have much good precedent, so maybe it's best for you guys to assign the ownership yourselves over the API per the link I sent earlier today. https://github.com/openshift/hive/blob/master/contrib/pkg/installmanager/installmanager.go#L406

We can come back to this in future if needed.

How do you all plan to use namespaces?

**Comment by cben** [comment]
We plan to create all objects in one namespace.
(We considered namespace-per-cluster vs putting everything in one namespace.  We figured we might not get permissions to create namespaces.)

permalink for above link to `SetControllerReference()` usage: https://github.com/openshift/hive/blob/54021425ba626acc45fce92b5b43a848c0e46ac7/contrib/pkg/installmanager/installmanager.go#L406

**Comment by dgoodwin** [comment]
I would recommend against everything in one namespace personally, I'd honestly rank that as the last option available. It's going to be really hard to debug, I don't necessarily know how it will scale, it's the least effective for protecting data in the event something is compromised, and there's more risk things will collide or someone will see something they shouldn't. Hive was designed for either (a) one customer account per namespace (potentially multiple clusters), or (b) one account per cluster. Both will give you much stronger separation of data.

We can definitely get you permissions to create and delete namespaces.

**Comment by cben** [comment]
About sharing secrets: our use case for wrapping Hive treats each cluster as fully independent, so we independent secrets per cluster.
- aws creds are provided by customers, their choice to provide same or different creds...
- pull secret is per customer, but our component won't store it and won't assume it, we'll get it from the user management component for each cluster creation request.  It's easier for us to create separate secrets per cluster.
- SSH keys we generate for each cluster.
- IIRC admin creds secret is generated by Hive per cluster, right?  For GC, is it owned by Hive?

**Comment by cben** [comment]
@jhernand @nimrodshn see https://github.com/openshift/hive/issues/109#issuecomment-441697526 let's reconsider using namespaces?

**Comment by jhernand** [comment]
The reason to not use namespaces is that the administrators of the clusters where we deploy our application don't want to give us permission to create/delete namespaces. And I kind of understand it. If we had that permission then we could accidentally delete other important namespaces. In addition we would need much broader permissions. For example, currently we need permissions to read/write secrets in one particular namespace, and we use a role binding for that, inside the relevant namespace. If we create a namespace per cluster then we would need permissions to read/write secrets in *all* namespaces, as we don't know the names of the namespaces in advance. Not sure if there is a way to limit this kind of permission to a set of namespaces, for example to all the namespaces starting with `uhc-`. @dgoodwin note that currently you are the owner of the production Hive cluster, so you may want to think that twice.

@cben @zgalor @nimrodshn @tzvatot I think that if we implement this it should be configurable, so that we can easily (with a command line option?) change from using namespaces to not using them, because I am afraid that this decision to allow us to create namespaces may change if the team that administers Hive changes.

Regarding the clean-up of secrets, we generate all of them, so we can clean-up them ourselves, it isn't a big deal.

**Comment by dgoodwin** [comment]
Closing per above, SD will own their own secrets for now. 

Namespace discussion will continue elsewhere.
