### ISSUE TITLE
Please report installation errors in the ClusterDeployment status

### ISSUE THREAD

**Issue by elad661** [openshift/hive#115]
Right now, the ClusterDeployment status is very vague, a boolean of `installed: true` or `installed: false`. However, it seems that in some cases Hive can know when the installer error'd out, for example:

https://github.com/openshift/hive/blob/fd92d98091acb208351657132998b1b1a7d58640/contrib/pkg/installmanager/installmanager.go#L198-L208

In these cases, it would be beneficial if the `status` of the ClusterDeployment would contain `error: true` or even `error: "failed due to installer error"`.

**Comment by dgoodwin** [comment]
The installer currently ignores some errors due to some possibly temporary instability in watching the bootstrap logs on a remote host. I think this code is still there thus why a lot of install errors are being reported as success.

Hive doesn't know specifically what went wrong, we're supposed to get an error code from installer and re-try the install if so, which will scrub all the resources from the first attempt before re-running. We could perhaps work on some specific errors codes with installer team and update status as it goes but it's unlikely we'll be able to effectively cover the multitude of things going wrong, especially as they're offloading most work to terraform. Something we can discuss with them in future though.

**Comment by elad661** [comment]
I've had a ClusterDeployment that failed due to quota issues, and the final line of the log was one with `failed due to installer error` with an exit code. This is not very informative, I agree, but at least it tells me that there was a failure. If this was present in the `ClusterDeployment` itself, I could've at least marked the cluster's status as `Error` in the clusters-service database...

**Comment by dgoodwin** [comment]
https://jira.coreos.com/browse/CO-172
