### ISSUE TITLE
Implement Openstack Hibernation

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/hive#1890]
Since ACM and hive itself supports deploying clusters to Openstack we should have a feature to hibernate Openstack clusters.

**Comment by usamaahmadkhan** [comment]
@2uasimojo what would be required for this to be put on the roadmap? If we have this our hibernation feature would be complete.
We are provisioning spokes on AWS/GCP/AZure/Openstack.

**Comment by 2uasimojo** [comment]
We track issues in Jira rather than GitHub, so I've opened https://issues.redhat.com/browse/HIVE-2042 for this. Please let me know once you are able to follow that card and I'll close this issue.

As for prioritization, we're pretty tight right now on feature work. However, we would be happy to accept outside contributions if you or someone you know might be able to implement this. We would be happy to provide the necessary guidance. It's not especially difficult code; the effort is more around the testing and validation. Let us know if you're interested in that.

**Comment by usamaahmadkhan** [comment]
Greate! I can submit a PR. I will go through the docs. Is there any other doc available apart from [hibernation doc](https://github.com/openshift/hive/blob/master/docs/hibernating-clusters.md)? Also how can I get access to the HIVE project on redhat JIRA?

**Comment by 2uasimojo** [comment]
The jira project is public I believe. You should just be able to create an account and get in.

For the implementation, I recommend simply following the pattern of the other [hibernation actuators](https://github.com/openshift/hive/tree/master/pkg/controller/hibernation). They need to implement the interfaces found [here](https://github.com/openshift/hive/blob/master/pkg/controller/hibernation/hibernation_actuator.go).

/cc @abraverm FYI

**Comment by abraverm** [comment]
FYI, Openstack hibernation is strange, at least the one I use, as it doesn't actually frees the resources (memory/cpu).
