### ISSUE TITLE
Availability of Hive in ARM 

### ISSUE THREAD

**Issue by fjcloud** [openshift/hive#2070]
Hello,

I didn't see Hive operator available on ARM, any plan for that ?

Thanks !

**Comment by 2uasimojo** [comment]
We don't have anything currently on our radar for this, but it would be a Good Thing™

Something deep in the recesses of my memory is saying that we tried it and it didn't work because hive doesn't currently have the logic to request the binaries from the release image that will _run on_ ARM but _install to_ x86. But I could be misremembering or making that up.

Perhaps you could try it for us :innocent:
