### ISSUE TITLE
Deleting an adopted cluster does not remove cluster from hive

### ISSUE THREAD

**Issue by faangbait** [openshift/hive#2371]
We provision ROSA (HCP) externally through terraform and adopt the cluster into hive for management (mostly for the syncsets).

When running `oc delete clusterdeployment`, the clusterdeployment resource remains in hive indefinitely. We work around this by editing the clusterdeployment resource and removing the finalizer.

Is this the best solution? If so, should it be documented somewhere?

**Comment by suhanime** [comment]
Hello! In general, hive doesn't distinguish between adopted or provisioned clusters once the adoption succeeds.
Could you give us some more info?
What's the reason the finalizer isn't getting removed? Is there some resource not getting deleted - like dnsZone? We check if the namespace is deleted before removing the finalizer.
Is the Deprovision job succeeding? Or is there any condition on the deprovision job that can point to a reason why it isn't?

**Comment by faangbait** [comment]
The deprovisioning job isn't _running_ (possibly because the HCP variant stands up control plane nodes inside RedHat-owned accounts).

**Comment by suhanime** [comment]
Okay, assuming you're able to deprovision the cluster external to hive, you can use [PreserveOnDelete](https://github.com/openshift/hive/blob/master/apis/hive/v1/clusterdeployment_types.go#L126:L129) to disconnect the cluster from hive and we'll stop reconciling on it.
I'm not sure if hive will be able to deprovision the cluster, since we don't support provisioning HCP clusters. If you try it anyways, the clusterdeployment status.conditions might have some info that could point to what's failing.
