### ISSUE TITLE
[Question] Why not merge `SelectorSyncSet` and `SyncSet` into one CRD?

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#601]
`SyncSet` can use cluster name while `SelectorSyncSet` can use cluster labels, why not merge those two CRD into one?

**Comment by dgoodwin** [comment]
This was our original plan but I believe the determining factor was namespaced vs global. We use namespaces as a small layer of isolation for clusters as those namespaces contain account credentials and certificates. In the case of SyncSet we're tying to specific clusters and thus it made sense to have them be a namespaced CRD. At the time of writing they could contain secrets (we since have a way to break those out), but in general for per cluster content we felt it was best to isolate those into the namespace with the cluster(s) they relate to.

SelectorSyncSet on the other hand we wanted to be a global resource as they typically span many or all clusters in all namespaces. We could do that with some kind of implicit rule like they live in the Hive namespace, but at the time we discussed it felt best to separate them given the differences in their scope.

**Comment by dgoodwin** [comment]
cc @csrwng @twiest in case I'm misremembering any of that.

**Comment by gyliu513** [comment]
Thanks @dgoodwin , but I think the `SelectorSyncSet` should be able to cover the case of `SyncSet`?

**Comment by gyliu513** [comment]
@dgoodwin this make sense, thanks!
