### ISSUE TITLE
Why setting hive admission deployment replica as 2

### ISSUE THREAD

**Issue by gyliu513** [openshift/hive#725]
This caused it is difficult to debug the admission controller pods, as I need to check which pod is handling the request.

What is the reason setting the replica as 2? Can we set this as 1? 

FYI @dgoodwin

**Comment by dgoodwin** [comment]
I'm really not sure why it's at two and I'm quite sure you can set it to one without causing any issues.

**Comment by gyliu513** [comment]
Yes, thanks @dgoodwin , but why not set it to 1 by default? This can help debug more easily, comments?

**Comment by gregsheremeta** [comment]
I've wondered this myself. @csrwng @staebler @twiest do you happen to know?

**Comment by twiest** [comment]
We have `failurePolicy: Fail` for the hiveadmission webhook config. What this means is that if the api server fails to connect to hiveadmission, all changes to hive objects that are validated by hiveadmission will fail.

Because of this we want a higher level of HA than what kube gives with a single pod. This saves us in cases where the node hosting hiveadmission fails and there is insufficient space to relocate hiveadmission to another worker node.

**Comment by gregsheremeta** [comment]
thanks, @twiest!

**Comment by gyliu513** [comment]
Thanks @twiest and @gregsheremeta , but for this case, I think there maybe some anti-affintiy policy needed for the deployment https://github.com/openshift/hive/blob/master/config/hiveadmission/deployment.yaml to make sure those two replicas will not be scheduled to same node.
