### ISSUE TITLE
Hive mapping of compute and infra nodes to worker nodes

### ISSUE THREAD

**Issue by tzvatot** [openshift/hive#80]
It's unclear how to map infra and compute nodes of a cluster to "worker" nodes in hive.

**Comment by dgoodwin** [comment]
Concept no longer formally exists in OpenShift 4.0, and many are outright opposed to it. You would have to roll your own solution, and that would be blocked today because you cannot have more than one worker machine pool yet, and you cannot apply specific labels/taints to machine pools. (both of which would be reasonable enhancements to request)

CC @twiest

**Comment by smarterclayton** [comment]
Worker needs to be renamed compute before we ship 4.0.  At this point, infra should be a possible configuration but we are considering not having it as the default.

**Comment by smarterclayton** [comment]
@aaronlevy @crawford ^ did you also expect this or have a different expectation?

**Comment by dgoodwin** [comment]
Worker is getting renamed to compute and master to control plane in https://github.com/openshift/installer/pull/1033. We will do the same in Hive once it's ready.

Hive will eventually support adding additional machine pools and tagging them. See https://jira.coreos.com/browse/CO-156
